### ISSUE TITLE
Impove order update failed messages

### ISSUE THREAD

**Issue by skyriakou** [commercetools/orders-update#21]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-7305

### Expected Behavior
give an information about states which couldn't change according to the allowed transistions (as we do it for API calls) instead of saying all imports were successfully, which they weren't apparently.

**Comment by VineetKumarKushwaha** [comment]
@skyriakou  Not sure what needs to be done here ? Could you please provide more details ?

**Comment by skyriakou** [comment]
@VineetKumarKushwaha - that is something for later that could be discussed with Jan or Daniel. I moved it to the bottom of the backlog so no need to think about it right now. Thanks.

**Comment by VineetKumarKushwaha** [comment]
Closing this issue as this is duplicated of https://github.com/commercetools/orders-update/issues/24 and the fix is realsed
