### ISSUE TITLE
Line item State Change via csv is not set

### ISSUE THREAD

**Issue by ashishhk** [commercetools/orders-update#24]
https://jira.commercetools.com/browse/SUPPORT-7305

**Comment by VineetKumarKushwaha** [comment]
After this we have to update the version of this package inside the express project.

**Comment by VineetKumarKushwaha** [comment]
This is identical to https://github.com/commercetools/orders-update/issues/21

**Comment by VineetKumarKushwaha** [comment]
Pushed and released v3.1.0
