### ISSUE TITLE
Add ReturnInfo update actions

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/orders-update#7]

**Comment by junajan** [comment]
According to the [documentation](https://dev.commercetools.com/http-api-projects-orders.html) there are only three actions for returnInfo:
 - Add ReturnInfo
 - Set ReturnShipmentState
 - Set ReturnPaymentState

I will implement them but for other actions (for example removing returnInfo, updating comment in returnItem and others) we will have to implement them first on an API.
